#!/bin/bash

if [ "$RUN_MODE" != "init" ] ; then

  echo "$GITHUB_PEM_KEY" > /gocd/github.pem
  chown go.go /gocd/github.pem
  chmod 0400  /gocd/github.pem
fi

# add go user to instance docker group
echo "vmdocker:x:497:go" >> /etc/group

/sbin/my_init
