#!/bin/bash -x

exec > >(tee /var/log/bh_init.log | logger -t bh_init -s 2>/dev/console) 2>&1

if [ -n "$GITHUB_PRIVATE_KEY" ] && [ "$ENABLE_GITHUB_PRIVATE_REPO_SUPPORT" = "yes" ] ; then

  echo "$GITHUB_PRIVATE_KEY" > /gocd/github.pem
  chown go.go /gocd/github.pem
  chmod 0400  /gocd/github.pem

  cat <<EOF
#
# IMPORTANT SECURITY NOTE:
#
# This image is containing your Github Private Key in /gocd/github.pem.
#
# DO NOT COMMIT AND PUSH THIS IMAGE TO A PUBLIC REPOSITORY!!!
#
EOF
fi

# add go user to instance docker group
echo "vmdocker:x:497:go" >> /etc/group

# force generation of new keystores
rm /etc/go/*store* 2> /dev/null

echo "$ADMIN_PASSWORD" >> /tmp/log
if [ -n "$ADMIN_PASSWORD" ] ; then

  HTPASSWD="$(echo -n "$ADMIN_PASSWORD" | htpasswd -i -n -s admin)"
  echo "$HTPASSWD" >> /tmp/log

  if [ ! -f "/etc/go/htpasswd" ] ; then 
    touch "/etc/go/htpasswd"
    chown go.go /etc/go/htpasswd
    chmod 600   /etc/go/htpasswd
  fi

  if grep "$HTPASSWD" /etc/go/htpasswd &> /dev/null ; then
    echo "change password" >> /tmp/log
    sed -i -e 's/^admin:.*/'"$HTPASSWD"'/' /etc/go/htpasswd
  else
    echo "add passord" >> /tmp/log
    echo "$HTPASSWD" >> /etc/go/htpasswd
  fi
fi 

/sbin/my_init
